; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:Marauder-Mini]
board = marauder-mini
board_build.partitions = support_files/custom_4Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/marauder-mini>
build_flags =
	${env.build_flags}
	-Iboards/marauder-mini
	-DMARAUDERMINI=1
	-DOTA_TAG='"marauder-mini"'

	-DROTATION=0
	-DHAS_BTN=1
	-DSEL_BTN=33
	-DUP_BTN=-1
	-DDW_BTN=-1
	-DR_BTN=12
	-DL_BTN=13

	-DBTN_ACT=LOW
	-DBTN_ALIAS='"Sel"'
	-DLED=-1
	-DLED_ON=LOW

	-DFP=1
	-DFM=1
	-DFG=2

	-DST7735_DRIVER=1
	-DTFT_WIDTH=128
	-DTFT_HEIGHT=160
	-DTFT_MISO=19
	-DTFT_MOSI=23
	-DTFT_SCLK=18
	-DTFT_BL=32
	-DTFT_CS=17
	-DTFT_DC=16
	-DTFT_RST=5

	# // 1.5" GREENTAB C 128x128
	-D GFX_BL=32
	-D TFT_IPS=0
	-D TFT_COL_OFS1=2
	-D TFT_ROW_OFS1=3
	-D TFT_COL_OFS2=0
	-D TFT_ROW_OFS2=0


	-DSDCARD_SPI_BUS=VSPI
	-DSDCARD_CS=4
	-DSDCARD_SCK=18
	-DSDCARD_MISO=19
	-DSDCARD_MOSI=23

	-DTFT_BRIGHT_CHANNEL=0
	-DTFT_BRIGHT_Bits=8
	-DTFT_BRIGHT_FREQ=5000

lib_ignore =
	SensorLib
	XPowersLib

[env:Marauder-v7]
board = marauder-mini
board_build.partitions = support_files/custom_4Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/marauder-mini>
build_flags =
	${env.build_flags}
	-Iboards/marauder-mini
	-DOTA_TAG='"marauder-v7"'
	-DMARAUDERMINI=1

	-DROTATION=0
	-DHAS_BTN=1
	-DSEL_BTN=34
	-DUP_BTN=36
	-DDW_BTN=35
	-DR_BTN=39
	-DL_BTN=13

	-DBTN_ACT=LOW
	-DBTN_ALIAS='"Sel"'
	-DLED=-1
	-DLED_ON=LOW

	-DFP=1
	-DFM=2
	-DFG=3

	-DILI9341_DRIVER=1
	-DTFT_WIDTH=240
	-DTFT_HEIGHT=320
	-DTFT_MISO=19
	-DTFT_MOSI=23
	-DTFT_SCLK=18
	-DTFT_CS=17
	-DTFT_DC=26
	-DTFT_RST=-1
	-DTFT_BL=32
	-DTOUCH_CS=-1

	-D GFX_BL=32
	-D TFT_IPS=0
	-D TFT_COL_OFS1=0
	-D TFT_ROW_OFS1=0
	-D TFT_COL_OFS2=0
	-D TFT_ROW_OFS2=0

	-DSDCARD_SPI_BUS=VSPI
	-DSDCARD_CS=4
	-DSDCARD_SCK=18
	-DSDCARD_MISO=19
	-DSDCARD_MOSI=23

	-DTFT_BRIGHT_CHANNEL=0
	-DTFT_BRIGHT_Bits=8
	-DTFT_BRIGHT_FREQ=5000

lib_ignore =
	SensorLib
	XPowersLib

[env:Awok-Mini]
extends = env:Marauder-Mini
board = awok-mini
board_build.partitions = support_files/custom_16Mb.csv
